// Custom TableGen backend for generating token definitions.
// Reads Tokens.td and emits TokenKinds.inc
#include <llvm/Support/CommandLine.h>
#include <llvm/Support/raw_ostream.h>
#include <llvm/TableGen/Main.h>
#include <llvm/TableGen/Record.h>
#include <span>
using namespace llvm;

namespace {

void header(raw_ostream& os, const StringRef ns) {
    os << "//\n";
    os << "// This file is part of lbc project\n";
    os << "// https://github.com/albeva/lbc\n";
    os << "//\n";
    os << "// This file is autogenerated. Do not modify\n";
    os << "#pragma once\n\n";
    os << "namespace " << ns << " {\n";
}

void footer(raw_ostream& os, const StringRef ns) {
    os << "} // namespace " << ns << "\n";
}

auto emitTokens(raw_ostream& os, const RecordKeeper& records) -> bool {
    const auto tokens = records.getAllDerivedDefinitions("Token");
    const auto categories = records.getAllDerivedDefinitions("TokenCategory");

    header(os, "lbc::lexer");

    // TokenCategory enum
    os << "enum class TokenCategory {\n";
    for (const auto* cat : categories) {
        os << "    " << cat->getName() << ",\n";
    }
    os << "};\n\n";

    // TokenKind enum
    os << "enum class TokenKind {\n";
    for (const auto* tok : tokens) {
        os << "    " << tok->getName() << ",\n";
    }
    os << "};\n\n";

    // Spelling lookup
    os << "constexpr auto tokenSpelling(TokenKind kind) -> std::string_view {\n";
    os << "    switch (kind) {\n";
    for (const auto* tok : tokens) {
        os << "    case TokenKind::" << tok->getName()
           << ": return \"" << tok->getValueAsString("Spelling") << "\"sv;\n";
    }
    os << "    }\n";
    os << "}\n\n";

    // Category lookup
    os << "constexpr auto tokenCategory(TokenKind kind) -> TokenCategory {\n";
    os << "    switch (kind) {\n";
    for (const auto* tok : tokens) {
        const auto* cat = tok->getValueAsDef("Category");
        os << "    case TokenKind::" << tok->getName()
           << ": return TokenCategory::" << cat->getName() << ";\n";
    }
    os << "    }\n";
    os << "}\n";

    footer(os, "lbc::lexer");

    return false;
}

} // namespace

auto main(const int argc, const char* argv[]) -> int {
    const auto span = std::span(argv, static_cast<std::size_t>(argc));
    cl::ParseCommandLineOptions(argc, argv);
    return TableGenMain(span.front(), emitTokens);
}
