//
// This file is part of lbc project
// https://github.com/albeva/lbc
//
// DO NOT MODIFY. This file is AUTO GENERATED.
//
// This file is generated by "lbc-ast-fwd-decl" from "Ast.td"
// clang-format off
#pragma once
namespace lbc {

class AstRoot;
class AstModule;
class AstType;
class AstBuiltInType;
class AstPointerType;
class AstReferenceType;
class AstStmt;
class AstStmtList;
class AstExprStmt;
class AstDeclareStmt;
class AstFuncStmt;
class AstReturnStmt;
class AstDimStmt;
class AstAssignStmt;
class AstIfStmt;
class AstDecl;
class AstVarDecl;
class AstFuncDecl;
class AstFuncParamDecl;
class AstExpr;
class AstCastExpr;
class AstVarExpr;
class AstCallExpr;
class AstLiteralExpr;
class AstUnaryExpr;
class AstBinaryExpr;
class AstMemberExpr;
} // namespace lbc
