//
// This file is part of lbc project
// https://github.com/albeva/lbc
//
// DO NOT MODIFY. This file is AUTOGENERATED.
//
// This file is generated by "lbc-ast-visitor" from "Ast.td"
// clang-format off
#pragma once
#include "Ast/Ast.hpp"

namespace lbc {

} // namespace lbc
