<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>bas</string>
	</array>
	<key>name</key>
	<string>lightbasic</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.lbc</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/'</string>
			<key>end</key>
			<string>'/</string>
			<key>name</key>
			<string>comment.lbc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([\[\]=,()_&amp;\*&lt;&gt;]|\.\.\.)</string>
			<key>name</key>
			<string>keyword.operator.lbc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(import|type|function|sub|declare|end|return|dim|as|if|then|else|for|to|step|next|continue|exit|do|loop))\b</string>
			<key>name</key>
			<string>keyword.control.lbc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(zstring|ubyte|byte|ushort|short|uinteger|integer|ulong|long|ulongint|longint|single|double|ptr|bool|any))\b</string>
			<key>name</key>
			<string>storage.typeExpr.lbc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(true|false|null))\b</string>
			<key>name</key>
			<string>constant.language.lbc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:(mod|or|and|not))\b</string>
			<key>name</key>
			<string>keyword.operator.lbc</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(-?[0-9]*\.?[0-9]+)\b</string>
			<key>name</key>
			<string>constant.numeric.lbc</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.lbc</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.lbc</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.lbc</string>
	<key>uuid</key>
	<string>2EE05B0E-22BA-4CE7-8481-CDD68C6AAE56</string>
</dict>
</plist>
