//
// This file is part of lbc project
// https://github.com/albeva/lbc
//
// DO NOT MODIFY. This file is AUTO GENERATED.
//
// This file is generated by "lbc-type-base" from "Types.td"
// clang-format off
#pragma once
#include "pch.hpp"
namespace lbc {

/**
 * Enumerate type kinds
 */
enum class TypeKind : std::uint8_t {
    Void,
    Null,
    Any,
    Bool,
    ZString,
    Byte,
    UByte,
    Short,
    UShort,
    Integer,
    UInteger,
    Long,
    ULong,
    Single,
    Double,
    Pointer,
    Reference,
    Qualified,
    Function,
};
/**
 * Base class for types
 */
class TypeBase {
public:
    NO_COPY_AND_MOVE(TypeBase)

    TypeBase() = delete;
    constexpr virtual ~TypeBase() noexcept = default;

    explicit constexpr TypeBase(const TypeKind kind)
    : m_kind(kind) { }

private:
    TypeKind m_kind;
};
} // namespace lbc
