//
// This file is part of lbc project
// https://github.com/albeva/lbc
//
// DO NOT MODIFY. This file is AUTO GENERATED.
//
// This file is generated by "lbc-diag-def" from "Diagnostics.td"
// clang-format off
#pragma once
#include "pch.hpp"
namespace lbc {

/**
 * DiagKind identifies a specific diagnostic and carries its static metadata
 */
struct DiagKind final {
    /**
     * Diagnostic identifier
     */
    enum Value : std::uint8_t { // NOLINT(*-use-enum-class)
        notImplemented,
        noInputFiles,
        inputFileNotFound,
        ambiguousOutput,
        cannotOpenOutput,
        backendVerificationFailed,
        optimizerFailed,
        codegenFailed,
        invalid,
        unterminatedString,
        invalidNumber,
        unexpected,
        expected,
        referenceNotLast,
        unsupportedLinkage,
        undeclaredIdentifier,
        useBeforeDefinition,
        redefinition,
        circularDependency,
        typeMismatch,
        invalidOperands,
        tooManyArguments,
        tooFewArguments,
        uninitializedReference,
        referenceToReference,
        pointerToReference,
        nullVariable,
        nonAddressableExpr,
        notCallable,
        invalidUnaryOperand,
        dereferencingAnyPtr,
        invalidReferenceInit,
        constToReference,
        notAssignable,
        assignToConst,
        invalidMoveOperand,
    };

    /**
     * Diagnostic subsystem
     */
    enum class Category : std::uint8_t {
        System,
        Lex,
        Parse,
        Sema,
    };

    /**
     * Total number of diagnostic kinds
     */
    static constexpr std::size_t COUNT = 36;

    /**
     * Default-construct to an uninitialized diagnostic kind
     */
    constexpr DiagKind() = default;

    /**
     * Implicitly convert from a Value enumerator
     */
    constexpr DiagKind(const Value value) // NOLINT(*-explicit-conversions)
    : m_value(value) { }

    /**
     * Return the underlying Value enum
     */
    [[nodiscard]] constexpr auto value() const {
        return m_value;
    }

    /**
     * Compare two DiagKind values for equality
     */
    [[nodiscard]] constexpr auto operator==(const DiagKind& other) const -> bool = default;

    /**
     * Compare against a raw Value enumerator
     */
    [[nodiscard]] constexpr auto operator==(const Value value) const -> bool {
        return m_value == value;
    }

    /**
     * Return the category for this diagnostic
     */
    [[nodiscard]] constexpr auto getCategory() const -> Category {
        switch (m_value) {
            case notImplemented:
            case noInputFiles:
            case inputFileNotFound:
            case ambiguousOutput:
            case cannotOpenOutput:
            case backendVerificationFailed:
            case optimizerFailed:
            case codegenFailed:
                return Category::System;
            case invalid:
            case unterminatedString:
            case invalidNumber:
                return Category::Lex;
            case unexpected:
            case expected:
            case referenceNotLast:
            case unsupportedLinkage:
                return Category::Parse;
            case undeclaredIdentifier:
            case useBeforeDefinition:
            case redefinition:
            case circularDependency:
            case typeMismatch:
            case invalidOperands:
            case tooManyArguments:
            case tooFewArguments:
            case uninitializedReference:
            case referenceToReference:
            case pointerToReference:
            case nullVariable:
            case nonAddressableExpr:
            case notCallable:
            case invalidUnaryOperand:
            case dereferencingAnyPtr:
            case invalidReferenceInit:
            case constToReference:
            case notAssignable:
            case assignToConst:
            case invalidMoveOperand:
                return Category::Sema;
        }
        std::unreachable();
    }

    /**
     * Return the severity for this diagnostic
     */
    [[nodiscard]] constexpr auto getSeverity() const -> llvm::SourceMgr::DiagKind {
        switch (m_value) {
            case notImplemented:
            case noInputFiles:
            case inputFileNotFound:
            case ambiguousOutput:
            case cannotOpenOutput:
            case backendVerificationFailed:
            case optimizerFailed:
            case codegenFailed:
            case invalid:
            case unterminatedString:
            case invalidNumber:
            case unexpected:
            case expected:
            case referenceNotLast:
            case unsupportedLinkage:
            case undeclaredIdentifier:
            case useBeforeDefinition:
            case redefinition:
            case circularDependency:
            case typeMismatch:
            case invalidOperands:
            case tooManyArguments:
            case tooFewArguments:
            case uninitializedReference:
            case referenceToReference:
            case pointerToReference:
            case nullVariable:
            case nonAddressableExpr:
            case notCallable:
            case invalidUnaryOperand:
            case dereferencingAnyPtr:
            case invalidReferenceInit:
            case constToReference:
            case notAssignable:
            case assignToConst:
            case invalidMoveOperand:
                return llvm::SourceMgr::DK_Error;
        }
        std::unreachable();
    }

    /**
     * Return the diagnostic code string
     */
    [[nodiscard]] constexpr auto getCode() const -> llvm::StringRef {
        switch (m_value) {
            case notImplemented: return "E0001";
            case noInputFiles: return "E0002";
            case inputFileNotFound: return "E0003";
            case ambiguousOutput: return "E0004";
            case cannotOpenOutput: return "E0005";
            case backendVerificationFailed: return "E0006";
            case optimizerFailed: return "E0007";
            case codegenFailed: return "E0008";
            case invalid: return "E0100";
            case unterminatedString: return "E0101";
            case invalidNumber: return "E0102";
            case unexpected: return "E0200";
            case expected: return "E0201";
            case referenceNotLast: return "E0202";
            case unsupportedLinkage: return "E0203";
            case undeclaredIdentifier: return "E0300";
            case useBeforeDefinition: return "E0301";
            case redefinition: return "E0302";
            case circularDependency: return "E0303";
            case typeMismatch: return "E0304";
            case invalidOperands: return "E0305";
            case tooManyArguments: return "E0306";
            case tooFewArguments: return "E0307";
            case uninitializedReference: return "E0308";
            case referenceToReference: return "E0309";
            case pointerToReference: return "E0310";
            case nullVariable: return "E0311";
            case nonAddressableExpr: return "E0312";
            case notCallable: return "E0313";
            case invalidUnaryOperand: return "E0314";
            case dereferencingAnyPtr: return "E0315";
            case invalidReferenceInit: return "E0316";
            case constToReference: return "E0317";
            case notAssignable: return "E0318";
            case assignToConst: return "E0319";
            case invalidMoveOperand: return "E0320";
        }
        std::unreachable();
    }

    /**
     * Return all Error diagnostics
     */
    [[nodiscard]] static consteval auto allErrors() -> std::array<DiagKind, 36> { // NOLINT(*-magic-numbers)
        return { notImplemented, noInputFiles, inputFileNotFound, ambiguousOutput, cannotOpenOutput, backendVerificationFailed, optimizerFailed, codegenFailed, invalid, unterminatedString, invalidNumber, unexpected, expected, referenceNotLast, unsupportedLinkage, undeclaredIdentifier, useBeforeDefinition, redefinition, circularDependency, typeMismatch, invalidOperands, tooManyArguments, tooFewArguments, uninitializedReference, referenceToReference, pointerToReference, nullVariable, nonAddressableExpr, notCallable, invalidUnaryOperand, dereferencingAnyPtr, invalidReferenceInit, constToReference, notAssignable, assignToConst, invalidMoveOperand };
    }

private:
    /// Underlying enumerator
    Value m_value;
};
} // namespace lbc

/**
 * Support using DiagKind with std::print and std::format
 */
template <>
struct std::formatter<lbc::DiagKind, char> final {
    constexpr static auto parse(std::format_parse_context& ctx) {
        return ctx.begin();
    }

    auto format(const lbc::DiagKind& value, auto& ctx) const {
        return std::format_to(ctx.out(), "{}", value.getCode());
    }
};

namespace lbc {

/**
 * Encapsulate a diagnostic kind and its formatted message
 */
using DiagMessage = std::pair<DiagKind, std::string>;

namespace diagnostics {
    // -------------------------------------------------------------------------
    // System
    // -------------------------------------------------------------------------

    /// Create notImplemented message
    [[nodiscard]] inline auto notImplemented() -> DiagMessage {
        return { DiagKind::notImplemented, "Not implemented" };
    }

    /// Create noInputFiles message
    [[nodiscard]] inline auto noInputFiles() -> DiagMessage {
        return { DiagKind::noInputFiles, "no input files" };
    }

    /// Create inputFileNotFound message
    [[nodiscard]] inline auto inputFileNotFound(const auto& path) -> DiagMessage {
        return { DiagKind::inputFileNotFound, std::format("input file not found: {}", path) };
    }

    /// Create ambiguousOutput message
    [[nodiscard]] inline auto ambiguousOutput() -> DiagMessage {
        return { DiagKind::ambiguousOutput, "cannot direct multiple input files to a single output file" };
    }

    /// Create cannotOpenOutput message
    [[nodiscard]] inline auto cannotOpenOutput(const auto& path, const auto& reason) -> DiagMessage {
        return { DiagKind::cannotOpenOutput, std::format("cannot open output file {}: {}", path, reason) };
    }

    /// Create backendVerificationFailed message
    [[nodiscard]] inline auto backendVerificationFailed() -> DiagMessage {
        return { DiagKind::backendVerificationFailed, "internal error: generated LLVM module failed verification" };
    }

    /// Create optimizerFailed message
    [[nodiscard]] inline auto optimizerFailed(const auto& reason) -> DiagMessage {
        return { DiagKind::optimizerFailed, std::format("optimizer failed: {}", reason) };
    }

    /// Create codegenFailed message
    [[nodiscard]] inline auto codegenFailed(const auto& reason) -> DiagMessage {
        return { DiagKind::codegenFailed, std::format("code generation failed: {}", reason) };
    }

    // -------------------------------------------------------------------------
    // Lex
    // -------------------------------------------------------------------------

    /// Create invalid message
    [[nodiscard]] inline auto invalid() -> DiagMessage {
        return { DiagKind::invalid, "invalid input" };
    }

    /// Create unterminatedString message
    [[nodiscard]] inline auto unterminatedString() -> DiagMessage {
        return { DiagKind::unterminatedString, "unterminated string literal" };
    }

    /// Create invalidNumber message
    [[nodiscard]] inline auto invalidNumber() -> DiagMessage {
        return { DiagKind::invalidNumber, "invalid number" };
    }

    // -------------------------------------------------------------------------
    // Parse
    // -------------------------------------------------------------------------

    /// Create unexpected message
    [[nodiscard]] inline auto unexpected(const auto& found) -> DiagMessage {
        return { DiagKind::unexpected, std::format("unexpected {}", found) };
    }

    /// Create expected message
    [[nodiscard]] inline auto expected(const auto& expected, const auto& found) -> DiagMessage {
        return { DiagKind::expected, std::format("expected {}, found {}", expected, found) };
    }

    /// Create referenceNotLast message
    [[nodiscard]] inline auto referenceNotLast() -> DiagMessage {
        return { DiagKind::referenceNotLast, "a reference must be the last qualifier in a type" };
    }

    /// Create unsupportedLinkage message
    [[nodiscard]] inline auto unsupportedLinkage(const auto& lang) -> DiagMessage {
        return { DiagKind::unsupportedLinkage, std::format("unsupported language linkage {}; only C is supported", lang) };
    }

    // -------------------------------------------------------------------------
    // Sema
    // -------------------------------------------------------------------------

    /// Create undeclaredIdentifier message
    [[nodiscard]] inline auto undeclaredIdentifier(const auto& name) -> DiagMessage {
        return { DiagKind::undeclaredIdentifier, std::format("use of undeclared identifier {}", name) };
    }

    /// Create useBeforeDefinition message
    [[nodiscard]] inline auto useBeforeDefinition(const auto& name) -> DiagMessage {
        return { DiagKind::useBeforeDefinition, std::format("use of identifier before definition {}", name) };
    }

    /// Create redefinition message
    [[nodiscard]] inline auto redefinition(const auto& name) -> DiagMessage {
        return { DiagKind::redefinition, std::format("redefinition of {}", name) };
    }

    /// Create circularDependency message
    [[nodiscard]] inline auto circularDependency(const auto& name) -> DiagMessage {
        return { DiagKind::circularDependency, std::format("circular dependency on {}", name) };
    }

    /// Create typeMismatch message
    [[nodiscard]] inline auto typeMismatch(const auto& from, const auto& to) -> DiagMessage {
        return { DiagKind::typeMismatch, std::format("cannot convert {} to {}", from, to) };
    }

    /// Create invalidOperands message
    [[nodiscard]] inline auto invalidOperands(const auto& op, const auto& left, const auto& right) -> DiagMessage {
        return { DiagKind::invalidOperands, std::format("invalid operands to {}: {} and {}", op, left, right) };
    }

    /// Create tooManyArguments message
    [[nodiscard]] inline auto tooManyArguments(const std::size_t expected, const std::size_t got) -> DiagMessage {
        return { DiagKind::tooManyArguments, std::format("too many arguments: expected {}, got {}", expected, got) };
    }

    /// Create tooFewArguments message
    [[nodiscard]] inline auto tooFewArguments(const std::size_t expected, const std::size_t got) -> DiagMessage {
        return { DiagKind::tooFewArguments, std::format("too few arguments: expected {}, got {}", expected, got) };
    }

    /// Create uninitializedReference message
    [[nodiscard]] inline auto uninitializedReference(const auto& name) -> DiagMessage {
        return { DiagKind::uninitializedReference, std::format("reference variable {} must be initialised", name) };
    }

    /// Create referenceToReference message
    [[nodiscard]] inline auto referenceToReference() -> DiagMessage {
        return { DiagKind::referenceToReference, "cannot create a reference to a reference" };
    }

    /// Create pointerToReference message
    [[nodiscard]] inline auto pointerToReference() -> DiagMessage {
        return { DiagKind::pointerToReference, "cannot create a pointer to a reference" };
    }

    /// Create nullVariable message
    [[nodiscard]] inline auto nullVariable() -> DiagMessage {
        return { DiagKind::nullVariable, "cannot declare a variable of type null" };
    }

    /// Create nonAddressableExpr message
    [[nodiscard]] inline auto nonAddressableExpr() -> DiagMessage {
        return { DiagKind::nonAddressableExpr, "cannot take address from expression" };
    }

    /// Create notCallable message
    [[nodiscard]] inline auto notCallable() -> DiagMessage {
        return { DiagKind::notCallable, "expression not a callable" };
    }

    /// Create invalidUnaryOperand message
    [[nodiscard]] inline auto invalidUnaryOperand(const auto& op, const auto& type) -> DiagMessage {
        return { DiagKind::invalidUnaryOperand, std::format("invalid operand to {}: {}", op, type) };
    }

    /// Create dereferencingAnyPtr message
    [[nodiscard]] inline auto dereferencingAnyPtr() -> DiagMessage {
        return { DiagKind::dereferencingAnyPtr, "dereferencing any ptr" };
    }

    /// Create invalidReferenceInit message
    [[nodiscard]] inline auto invalidReferenceInit() -> DiagMessage {
        return { DiagKind::invalidReferenceInit, "Cannot initialize reference from given expression" };
    }

    /// Create constToReference message
    [[nodiscard]] inline auto constToReference() -> DiagMessage {
        return { DiagKind::constToReference, "cannot apply CONST to a reference" };
    }

    /// Create notAssignable message
    [[nodiscard]] inline auto notAssignable() -> DiagMessage {
        return { DiagKind::notAssignable, "expression is not assignable" };
    }

    /// Create assignToConst message
    [[nodiscard]] inline auto assignToConst() -> DiagMessage {
        return { DiagKind::assignToConst, "cannot assign to a constant value" };
    }

    /// Create invalidMoveOperand message
    [[nodiscard]] inline auto invalidMoveOperand() -> DiagMessage {
        return { DiagKind::invalidMoveOperand, "cannot MOVE a temporary value" };
    }

}
} // namespace lbc
