//
// This file is part of lbc project
// https://github.com/albeva/lbc
//
// DO NOT MODIFY. This file is AUTO GENERATED.
//
// This file is generated by "lbc-diag-impl" from "Diagnostics.td"
// clang-format off
#pragma once

namespace lbc {

} // namespace lbc
