//
// This file is part of lbc project
// https://github.com/albeva/lbc
//
// DO NOT MODIFY. This file is AUTO GENERATED.
//
// This file is generated by "lbc-ir-inst-def" from "Instructions.td"
// clang-format off
#pragma once
#include "pch.hpp"
#include "IR/Instruction.hpp"
namespace lbc::ir {

} // namespace lbc::ir
