//
// This file is part of lbc project
// https://github.com/albeva/lbc
//
// DO NOT MODIFY. This file is AUTO GENERATED.
//
// This file is generated by "lbc-ir-inst-def" from "Instructions.td"
// clang-format off
#pragma once
#include "pch.hpp"
#include "IR/Instruction.hpp"
namespace lbc::ir {

class Block;
class NamedValue;
class Type;
class Value;
/**
 * Enumerates all concrete IR node kinds.
 * Values are ordered by group for efficient range-based membership checks.
 */
enum class IrKind : std::uint8_t {
    Store,
    Retain,
    Release,
    Jmp,
    CondJmp,
    Ret,
    Cast,
    Load,
    AddrOf,
    Call,
    Neg,
    Not,
    Add,
    Sub,
    Mul,
    Div,
    Mod,
    And,
    Or,
    Eq,
    Ne,
    Lt,
    Le,
    Gt,
    Ge,
    Var,
};

// -----------------------------------------------------------------------------
// Root nodes
// -----------------------------------------------------------------------------

/**
 * The root of IR instructions
 */
class [[nodiscard]] IrRoot : public llvm::ilist_node<IrRoot> {
public:
    NO_COPY_AND_MOVE(IrRoot)

protected:
    /**
     * Construct an IrRoot node
     */
    constexpr explicit IrRoot(
        const IrKind kind
    )
    : m_kind(kind) {}

public:
    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const IrRoot* /*node*/) -> bool {
        return true;
    }

    /// Number of IR leaf nodes
    static constexpr std::size_t NODE_COUNT = 26;

    /// Get the kind discriminator for this node
    [[nodiscard]] constexpr auto getKind() const -> IrKind {
        return m_kind;
    }

    /// Get IR node class name
    [[nodiscard]] constexpr auto getClassName() const -> llvm::StringRef {
        const auto index = static_cast<std::size_t>(m_kind);
        return kClassNames.at(index);
    }

    /// Get instruction mnemonic
    [[nodiscard]] constexpr auto getMnemonic() const -> llvm::StringRef {
        const auto index = static_cast<std::size_t>(m_kind);
        return kMnemonics.at(index);
    }

private:
    IrKind m_kind;
    static constexpr std::array<llvm::StringRef, NODE_COUNT> kClassNames {
        "IrStore",
        "IrRetain",
        "IrRelease",
        "IrJmp",
        "IrCondJmp",
        "IrRet",
        "IrCast",
        "IrLoad",
        "IrAddrOf",
        "IrCall",
        "IrNeg",
        "IrNot",
        "IrAdd",
        "IrSub",
        "IrMul",
        "IrDiv",
        "IrMod",
        "IrAnd",
        "IrOr",
        "IrEq",
        "IrNe",
        "IrLt",
        "IrLe",
        "IrGt",
        "IrGe",
        "IrVar"
    };
    static constexpr std::array<llvm::StringRef, NODE_COUNT> kMnemonics {
        "store",
        "retain",
        "release",
        "jmp",
        "jmp",
        "ret",
        "cast",
        "load",
        "addrof",
        "call",
        "neg",
        "not",
        "add",
        "sub",
        "mul",
        "div",
        "mod",
        "and",
        "or",
        "eq",
        "ne",
        "lt",
        "le",
        "gt",
        "ge",
        "var"
    };
};

/**
 * Store value through pointer
 */
class [[nodiscard]] IrStore final : public IrRoot {
public:
    /**
     * Construct an IrStore node
     */
    constexpr IrStore(
        NamedValue* dest,
        Value* src
    )
    : IrRoot(IrKind::Store)
    , m_dest(dest)
    , m_src(src) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const IrRoot* node) -> bool {
        return node->getKind() == IrKind::Store;
    }

    /// Get the dest
    [[nodiscard]] constexpr auto getDest() const -> NamedValue* {
        return m_dest;
    }

    /// Get the src
    [[nodiscard]] constexpr auto getSrc() const -> Value* {
        return m_src;
    }

private:
    NamedValue* m_dest;
    Value* m_src;
};

/**
 * Increment reference count
 */
class [[nodiscard]] IrRetain final : public IrRoot {
public:
    /**
     * Construct an IrRetain node
     */
    constexpr explicit IrRetain(
        NamedValue* operand
    )
    : IrRoot(IrKind::Retain)
    , m_operand(operand) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const IrRoot* node) -> bool {
        return node->getKind() == IrKind::Retain;
    }

    /// Get the operand
    [[nodiscard]] constexpr auto getOperand() const -> NamedValue* {
        return m_operand;
    }

private:
    NamedValue* m_operand;
};

/**
 * Decrement reference count
 */
class [[nodiscard]] IrRelease final : public IrRoot {
public:
    /**
     * Construct an IrRelease node
     */
    constexpr explicit IrRelease(
        NamedValue* operand
    )
    : IrRoot(IrKind::Release)
    , m_operand(operand) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const IrRoot* node) -> bool {
        return node->getKind() == IrKind::Release;
    }

    /// Get the operand
    [[nodiscard]] constexpr auto getOperand() const -> NamedValue* {
        return m_operand;
    }

private:
    NamedValue* m_operand;
};

// -----------------------------------------------------------------------------
// Terminator nodes
// -----------------------------------------------------------------------------

/**
 * Abstract base for all Terminating instructions nodes
 */
class [[nodiscard]] IrTerminator : public IrRoot {
protected:
    using IrRoot::IrRoot;

public:
    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const IrRoot* node) -> bool {
        return node->getKind() >= IrKind::Jmp && node->getKind() <= IrKind::Ret;
    }
};

/**
 * Unconditional branch
 */
class [[nodiscard]] IrJmp final : public IrTerminator {
public:
    /**
     * Construct an IrJmp node
     */
    constexpr explicit IrJmp(
        Block* destination
    )
    : IrTerminator(IrKind::Jmp)
    , m_destination(destination) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const IrRoot* node) -> bool {
        return node->getKind() == IrKind::Jmp;
    }

    /// Get the destination
    [[nodiscard]] constexpr auto getDestination() const -> Block* {
        return m_destination;
    }

private:
    Block* m_destination;
};

/**
 * Conditional branch
 */
class [[nodiscard]] IrCondJmp final : public IrTerminator {
public:
    /**
     * Construct an IrCondJmp node
     */
    constexpr IrCondJmp(
        Value* condition,
        Block* trueBlock,
        Block* falseBlock
    )
    : IrTerminator(IrKind::CondJmp)
    , m_condition(condition)
    , m_trueBlock(trueBlock)
    , m_falseBlock(falseBlock) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const IrRoot* node) -> bool {
        return node->getKind() == IrKind::CondJmp;
    }

    /// Get the condition
    [[nodiscard]] constexpr auto getCondition() const -> Value* {
        return m_condition;
    }

    /// Get the trueBlock
    [[nodiscard]] constexpr auto getTrueBlock() const -> Block* {
        return m_trueBlock;
    }

    /// Get the falseBlock
    [[nodiscard]] constexpr auto getFalseBlock() const -> Block* {
        return m_falseBlock;
    }

private:
    Value* m_condition;
    Block* m_trueBlock;
    Block* m_falseBlock;
};

/**
 * Return value
 */
class [[nodiscard]] IrRet final : public IrTerminator {
public:
    /**
     * Construct an IrRet node
     */
    constexpr explicit IrRet(
        Value* value
    )
    : IrTerminator(IrKind::Ret)
    , m_value(value) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const IrRoot* node) -> bool {
        return node->getKind() == IrKind::Ret;
    }

    /// Get the value
    [[nodiscard]] constexpr auto getValue() const -> Value* {
        return m_value;
    }

private:
    Value* m_value;
};

// -----------------------------------------------------------------------------
// Expression nodes
// -----------------------------------------------------------------------------

/**
 * Abstract base for all Expression returning a result nodes
 */
class [[nodiscard]] IrExpression : public IrRoot {
protected:
    /**
     * Construct an IrExpression node
     */
    constexpr explicit IrExpression(
        const IrKind kind,
        NamedValue* result
    )
    : IrRoot(kind)
    , m_result(result) {}

public:
    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const IrRoot* node) -> bool {
        return node->getKind() >= IrKind::Cast && node->getKind() <= IrKind::Ge;
    }

    /// Get the result
    [[nodiscard]] constexpr auto getResult() const -> NamedValue* {
        return m_result;
    }

private:
    NamedValue* m_result;
};

/**
 * Type conversion
 */
class [[nodiscard]] IrCast final : public IrExpression {
public:
    /**
     * Construct an IrCast node
     */
    constexpr IrCast(
        NamedValue* result,
        const Type* targetType,
        Value* operand
    )
    : IrExpression(IrKind::Cast, result)
    , m_targetType(targetType)
    , m_operand(operand) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const IrRoot* node) -> bool {
        return node->getKind() == IrKind::Cast;
    }

    /// Get the targetType
    [[nodiscard]] constexpr auto getTargetType() const -> const Type* {
        return m_targetType;
    }

    /// Get the operand
    [[nodiscard]] constexpr auto getOperand() const -> Value* {
        return m_operand;
    }

private:
    const Type* m_targetType;
    Value* m_operand;
};

/**
 * Load value through pointer
 */
class [[nodiscard]] IrLoad final : public IrExpression {
public:
    /**
     * Construct an IrLoad node
     */
    constexpr IrLoad(
        NamedValue* result,
        Value* source
    )
    : IrExpression(IrKind::Load, result)
    , m_source(source) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const IrRoot* node) -> bool {
        return node->getKind() == IrKind::Load;
    }

    /// Get the source
    [[nodiscard]] constexpr auto getSource() const -> Value* {
        return m_source;
    }

private:
    Value* m_source;
};

/**
 * Take address of a variable
 */
class [[nodiscard]] IrAddrOf final : public IrExpression {
public:
    /**
     * Construct an IrAddrOf node
     */
    constexpr IrAddrOf(
        NamedValue* result,
        Value* operand
    )
    : IrExpression(IrKind::AddrOf, result)
    , m_operand(operand) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const IrRoot* node) -> bool {
        return node->getKind() == IrKind::AddrOf;
    }

    /// Get the operand
    [[nodiscard]] constexpr auto getOperand() const -> Value* {
        return m_operand;
    }

private:
    Value* m_operand;
};

/**
 * Void function call
 */
class [[nodiscard]] IrCall final : public IrExpression {
public:
    /**
     * Construct an IrCall node
     */
    constexpr IrCall(
        NamedValue* result,
        NamedValue* callee,
        const std::span<Value*> args
    )
    : IrExpression(IrKind::Call, result)
    , m_callee(callee)
    , m_args(args) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const IrRoot* node) -> bool {
        return node->getKind() == IrKind::Call;
    }

    /// Get the callee
    [[nodiscard]] constexpr auto getCallee() const -> NamedValue* {
        return m_callee;
    }

    /// Get the args
    [[nodiscard]] constexpr auto getArgs() const -> std::span<Value*> {
        return m_args;
    }

private:
    NamedValue* m_callee;
    std::span<Value*> m_args;
};

// -----------------------------------------------------------------------------
// Unary nodes
// -----------------------------------------------------------------------------

/**
 * Abstract base for all Unary expressions nodes
 */
class [[nodiscard]] IrUnary : public IrExpression {
protected:
    /**
     * Construct an IrUnary node
     */
    constexpr IrUnary(
        const IrKind kind,
        NamedValue* result,
        Value* operand
    )
    : IrExpression(kind, result)
    , m_operand(operand) {}

public:
    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const IrRoot* node) -> bool {
        return node->getKind() >= IrKind::Neg && node->getKind() <= IrKind::Not;
    }

    /// Get the operand
    [[nodiscard]] constexpr auto getOperand() const -> Value* {
        return m_operand;
    }

private:
    Value* m_operand;
};

/**
 * Arithmetic negation
 */
class [[nodiscard]] IrNeg final : public IrUnary {
public:
    /**
     * Construct an IrNeg node
     */
    constexpr IrNeg(
        NamedValue* result,
        Value* operand
    )
    : IrUnary(IrKind::Neg, result, operand) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const IrRoot* node) -> bool {
        return node->getKind() == IrKind::Neg;
    }
};

/**
 * Logical NOT
 */
class [[nodiscard]] IrNot final : public IrUnary {
public:
    /**
     * Construct an IrNot node
     */
    constexpr IrNot(
        NamedValue* result,
        Value* operand
    )
    : IrUnary(IrKind::Not, result, operand) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const IrRoot* node) -> bool {
        return node->getKind() == IrKind::Not;
    }
};

// -----------------------------------------------------------------------------
// Binary nodes
// -----------------------------------------------------------------------------

/**
 * Abstract base for all Unary expressions nodes
 */
class [[nodiscard]] IrBinary : public IrExpression {
protected:
    /**
     * Construct an IrBinary node
     */
    constexpr IrBinary(
        const IrKind kind,
        NamedValue* result,
        Value* lhs,
        Value* rhs
    )
    : IrExpression(kind, result)
    , m_lhs(lhs)
    , m_rhs(rhs) {}

public:
    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const IrRoot* node) -> bool {
        return node->getKind() >= IrKind::Add && node->getKind() <= IrKind::Ge;
    }

    /// Get the lhs
    [[nodiscard]] constexpr auto getLhs() const -> Value* {
        return m_lhs;
    }

    /// Get the rhs
    [[nodiscard]] constexpr auto getRhs() const -> Value* {
        return m_rhs;
    }

private:
    Value* m_lhs;
    Value* m_rhs;
};

/**
 * Addition
 */
class [[nodiscard]] IrAdd final : public IrBinary {
public:
    /**
     * Construct an IrAdd node
     */
    constexpr IrAdd(
        NamedValue* result,
        Value* lhs,
        Value* rhs
    )
    : IrBinary(IrKind::Add, result, lhs, rhs) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const IrRoot* node) -> bool {
        return node->getKind() == IrKind::Add;
    }
};

/**
 * Subtraction
 */
class [[nodiscard]] IrSub final : public IrBinary {
public:
    /**
     * Construct an IrSub node
     */
    constexpr IrSub(
        NamedValue* result,
        Value* lhs,
        Value* rhs
    )
    : IrBinary(IrKind::Sub, result, lhs, rhs) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const IrRoot* node) -> bool {
        return node->getKind() == IrKind::Sub;
    }
};

/**
 * Multiplication
 */
class [[nodiscard]] IrMul final : public IrBinary {
public:
    /**
     * Construct an IrMul node
     */
    constexpr IrMul(
        NamedValue* result,
        Value* lhs,
        Value* rhs
    )
    : IrBinary(IrKind::Mul, result, lhs, rhs) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const IrRoot* node) -> bool {
        return node->getKind() == IrKind::Mul;
    }
};

/**
 * Division
 */
class [[nodiscard]] IrDiv final : public IrBinary {
public:
    /**
     * Construct an IrDiv node
     */
    constexpr IrDiv(
        NamedValue* result,
        Value* lhs,
        Value* rhs
    )
    : IrBinary(IrKind::Div, result, lhs, rhs) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const IrRoot* node) -> bool {
        return node->getKind() == IrKind::Div;
    }
};

/**
 * Modulo
 */
class [[nodiscard]] IrMod final : public IrBinary {
public:
    /**
     * Construct an IrMod node
     */
    constexpr IrMod(
        NamedValue* result,
        Value* lhs,
        Value* rhs
    )
    : IrBinary(IrKind::Mod, result, lhs, rhs) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const IrRoot* node) -> bool {
        return node->getKind() == IrKind::Mod;
    }
};

/**
 * Logical AND
 */
class [[nodiscard]] IrAnd final : public IrBinary {
public:
    /**
     * Construct an IrAnd node
     */
    constexpr IrAnd(
        NamedValue* result,
        Value* lhs,
        Value* rhs
    )
    : IrBinary(IrKind::And, result, lhs, rhs) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const IrRoot* node) -> bool {
        return node->getKind() == IrKind::And;
    }
};

/**
 * Logical OR
 */
class [[nodiscard]] IrOr final : public IrBinary {
public:
    /**
     * Construct an IrOr node
     */
    constexpr IrOr(
        NamedValue* result,
        Value* lhs,
        Value* rhs
    )
    : IrBinary(IrKind::Or, result, lhs, rhs) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const IrRoot* node) -> bool {
        return node->getKind() == IrKind::Or;
    }
};

// -----------------------------------------------------------------------------
// Comparison nodes
// -----------------------------------------------------------------------------

/**
 * Abstract base for all Comparison expressions nodes
 */
class [[nodiscard]] IrComparison : public IrBinary {
protected:
    using IrBinary::IrBinary;

public:
    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const IrRoot* node) -> bool {
        return node->getKind() >= IrKind::Eq && node->getKind() <= IrKind::Ge;
    }
};

/**
 * Equal
 */
class [[nodiscard]] IrEq final : public IrComparison {
public:
    /**
     * Construct an IrEq node
     */
    constexpr IrEq(
        NamedValue* result,
        Value* lhs,
        Value* rhs
    )
    : IrComparison(IrKind::Eq, result, lhs, rhs) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const IrRoot* node) -> bool {
        return node->getKind() == IrKind::Eq;
    }
};

/**
 * Not equal
 */
class [[nodiscard]] IrNe final : public IrComparison {
public:
    /**
     * Construct an IrNe node
     */
    constexpr IrNe(
        NamedValue* result,
        Value* lhs,
        Value* rhs
    )
    : IrComparison(IrKind::Ne, result, lhs, rhs) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const IrRoot* node) -> bool {
        return node->getKind() == IrKind::Ne;
    }
};

/**
 * Less than
 */
class [[nodiscard]] IrLt final : public IrComparison {
public:
    /**
     * Construct an IrLt node
     */
    constexpr IrLt(
        NamedValue* result,
        Value* lhs,
        Value* rhs
    )
    : IrComparison(IrKind::Lt, result, lhs, rhs) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const IrRoot* node) -> bool {
        return node->getKind() == IrKind::Lt;
    }
};

/**
 * Less than or equal
 */
class [[nodiscard]] IrLe final : public IrComparison {
public:
    /**
     * Construct an IrLe node
     */
    constexpr IrLe(
        NamedValue* result,
        Value* lhs,
        Value* rhs
    )
    : IrComparison(IrKind::Le, result, lhs, rhs) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const IrRoot* node) -> bool {
        return node->getKind() == IrKind::Le;
    }
};

/**
 * Greater than
 */
class [[nodiscard]] IrGt final : public IrComparison {
public:
    /**
     * Construct an IrGt node
     */
    constexpr IrGt(
        NamedValue* result,
        Value* lhs,
        Value* rhs
    )
    : IrComparison(IrKind::Gt, result, lhs, rhs) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const IrRoot* node) -> bool {
        return node->getKind() == IrKind::Gt;
    }
};

/**
 * Greater than or equal
 */
class [[nodiscard]] IrGe final : public IrComparison {
public:
    /**
     * Construct an IrGe node
     */
    constexpr IrGe(
        NamedValue* result,
        Value* lhs,
        Value* rhs
    )
    : IrComparison(IrKind::Ge, result, lhs, rhs) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const IrRoot* node) -> bool {
        return node->getKind() == IrKind::Ge;
    }
};

// -----------------------------------------------------------------------------
// Declaration nodes
// -----------------------------------------------------------------------------

/**
 * Abstract base for all Declaration instructions nodes
 */
class [[nodiscard]] IrDeclaration : public IrRoot {
protected:
    /**
     * Construct an IrDeclaration node
     */
    constexpr explicit IrDeclaration(
        const IrKind kind,
        NamedValue* result
    )
    : IrRoot(kind)
    , m_result(result) {}

public:
    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const IrRoot* node) -> bool {
        return node->getKind() == IrKind::Var;
    }

    /// Get the result
    [[nodiscard]] constexpr auto getResult() const -> NamedValue* {
        return m_result;
    }

private:
    NamedValue* m_result;
};

/**
 * Variable declaration
 */
class [[nodiscard]] IrVar final : public IrDeclaration {
public:
    /**
     * Construct an IrVar node
     */
    constexpr IrVar(
        NamedValue* result,
        const Type* type
    )
    : IrDeclaration(IrKind::Var, result)
    , m_type(type) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const IrRoot* node) -> bool {
        return node->getKind() == IrKind::Var;
    }

    /// Get the type
    [[nodiscard]] constexpr auto getType() const -> const Type* {
        return m_type;
    }

private:
    const Type* m_type;
};

} // namespace lbc::ir
