//
// This file is part of lbc project
// https://github.com/albeva/lbc
//
// DO NOT MODIFY. This file is AUTO GENERATED.
//
// This file is generated by "lbc-ir-inst-def" from "Instructions.td"
// clang-format off
#pragma once
#include "pch.hpp"

namespace lbc {
    class Type;
}

namespace lbc::ir::lib {

class BasicBlock;
class NamedValue;
class Function;
class Value;

/**
 * Enumerates all concrete tree nodes
 */
enum class IrKind : std::uint8_t {
    Store,
    Retain,
    Release,
    Jmp,
    CondJmp,
    Ret,
    Cast,
    Load,
    AddrOf,
    Call,
    Neg,
    Not,
    Add,
    Sub,
    Mul,
    Div,
    Mod,
    And,
    Or,
    Eq,
    Ne,
    Lt,
    Le,
    Gt,
    Ge,
    Var,
};

// -----------------------------------------------------------------------------
// Root nodes
// -----------------------------------------------------------------------------

/**
 * The root of IR instructions
 */
class [[nodiscard]] Instruction : public llvm::ilist_node<Instruction> {
public:
    NO_COPY_AND_MOVE(Instruction)

protected:
    /**
     * Construct an Instruction node
     */
    constexpr explicit Instruction(
        const IrKind kind
    )
    : m_kind(kind) {}

public:
    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const Instruction* /*node*/) -> bool {
        return true;
    }

    /// Number of leaf nodes
    static constexpr std::size_t NODE_COUNT = 26;

    /// Get the kind discriminator for this node
    [[nodiscard]] constexpr auto getKind() const -> IrKind {
        return m_kind;
    }

    /// Get node class name
    [[nodiscard]] constexpr auto getClassName() const -> llvm::StringRef {
        const auto index = static_cast<std::size_t>(m_kind);
        return kClassNames.at(index);
    }

    /// Get instruction mnemonic
    [[nodiscard]] constexpr auto getMnemonic() const -> llvm::StringRef {
        const auto index = static_cast<std::size_t>(m_kind);
        return kMnemonics.at(index);
    }

private:
    IrKind m_kind;
    static constexpr std::array<llvm::StringRef, NODE_COUNT> kClassNames {
        "StoreInstr",
        "RetainInstr",
        "ReleaseInstr",
        "JmpInstr",
        "CondJmpInstr",
        "RetInstr",
        "CastInstr",
        "LoadInstr",
        "AddrOfInstr",
        "CallInstr",
        "NegInstr",
        "NotInstr",
        "AddInstr",
        "SubInstr",
        "MulInstr",
        "DivInstr",
        "ModInstr",
        "AndInstr",
        "OrInstr",
        "EqInstr",
        "NeInstr",
        "LtInstr",
        "LeInstr",
        "GtInstr",
        "GeInstr",
        "VarInstr"
    };
    static constexpr std::array<llvm::StringRef, NODE_COUNT> kMnemonics {
        "store",
        "retain",
        "release",
        "jmp",
        "jmp",
        "ret",
        "cast",
        "load",
        "addrof",
        "call",
        "neg",
        "not",
        "add",
        "sub",
        "mul",
        "div",
        "mod",
        "and",
        "or",
        "eq",
        "ne",
        "lt",
        "le",
        "gt",
        "ge",
        "var"
    };
};

/**
 * Store value through pointer
 */
class [[nodiscard]] StoreInstr final : public Instruction {
public:
    /**
     * Construct a StoreInstr node
     */
    constexpr StoreInstr(
        NamedValue* dest,
        Value* src
    )
    : Instruction(IrKind::Store)
    , m_dest(dest)
    , m_src(src) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const Instruction* node) -> bool {
        return node->getKind() == IrKind::Store;
    }

    /// Get the dest
    [[nodiscard]] constexpr auto getDest() const -> NamedValue* {
        return m_dest;
    }

    /// Get the src
    [[nodiscard]] constexpr auto getSrc() const -> Value* {
        return m_src;
    }

private:
    NamedValue* m_dest;
    Value* m_src;
};

/**
 * Increment reference count
 */
class [[nodiscard]] RetainInstr final : public Instruction {
public:
    /**
     * Construct a RetainInstr node
     */
    constexpr explicit RetainInstr(
        NamedValue* operand
    )
    : Instruction(IrKind::Retain)
    , m_operand(operand) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const Instruction* node) -> bool {
        return node->getKind() == IrKind::Retain;
    }

    /// Get the operand
    [[nodiscard]] constexpr auto getOperand() const -> NamedValue* {
        return m_operand;
    }

private:
    NamedValue* m_operand;
};

/**
 * Decrement reference count
 */
class [[nodiscard]] ReleaseInstr final : public Instruction {
public:
    /**
     * Construct a ReleaseInstr node
     */
    constexpr explicit ReleaseInstr(
        NamedValue* operand
    )
    : Instruction(IrKind::Release)
    , m_operand(operand) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const Instruction* node) -> bool {
        return node->getKind() == IrKind::Release;
    }

    /// Get the operand
    [[nodiscard]] constexpr auto getOperand() const -> NamedValue* {
        return m_operand;
    }

private:
    NamedValue* m_operand;
};

// -----------------------------------------------------------------------------
// Terminator nodes
// -----------------------------------------------------------------------------

/**
 * Abstract base for all Terminating instructions nodes
 */
class [[nodiscard]] IrTerminator : public Instruction {
protected:
    using Instruction::Instruction;

public:
    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const Instruction* node) -> bool {
        return node->getKind() >= IrKind::Jmp && node->getKind() <= IrKind::Ret;
    }
};

/**
 * Unconditional branch
 */
class [[nodiscard]] JmpInstr final : public IrTerminator {
public:
    /**
     * Construct a JmpInstr node
     */
    constexpr explicit JmpInstr(
        BasicBlock* destination
    )
    : IrTerminator(IrKind::Jmp)
    , m_destination(destination) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const Instruction* node) -> bool {
        return node->getKind() == IrKind::Jmp;
    }

    /// Get the destination
    [[nodiscard]] constexpr auto getDestination() const -> BasicBlock* {
        return m_destination;
    }

private:
    BasicBlock* m_destination;
};

/**
 * Conditional branch
 */
class [[nodiscard]] CondJmpInstr final : public IrTerminator {
public:
    /**
     * Construct a CondJmpInstr node
     */
    constexpr CondJmpInstr(
        Value* condition,
        BasicBlock* trueBlock,
        BasicBlock* falseBlock
    )
    : IrTerminator(IrKind::CondJmp)
    , m_condition(condition)
    , m_trueBlock(trueBlock)
    , m_falseBlock(falseBlock) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const Instruction* node) -> bool {
        return node->getKind() == IrKind::CondJmp;
    }

    /// Get the condition
    [[nodiscard]] constexpr auto getCondition() const -> Value* {
        return m_condition;
    }

    /// Get the trueBlock
    [[nodiscard]] constexpr auto getTrueBlock() const -> BasicBlock* {
        return m_trueBlock;
    }

    /// Get the falseBlock
    [[nodiscard]] constexpr auto getFalseBlock() const -> BasicBlock* {
        return m_falseBlock;
    }

private:
    Value* m_condition;
    BasicBlock* m_trueBlock;
    BasicBlock* m_falseBlock;
};

/**
 * Return value
 */
class [[nodiscard]] RetInstr final : public IrTerminator {
public:
    /**
     * Construct a RetInstr node
     */
    constexpr explicit RetInstr(
        Value* value
    )
    : IrTerminator(IrKind::Ret)
    , m_value(value) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const Instruction* node) -> bool {
        return node->getKind() == IrKind::Ret;
    }

    /// Get the value
    [[nodiscard]] constexpr auto getValue() const -> Value* {
        return m_value;
    }

private:
    Value* m_value;
};

// -----------------------------------------------------------------------------
// Expression nodes
// -----------------------------------------------------------------------------

/**
 * Abstract base for all Expression returning a result nodes
 */
class [[nodiscard]] IrExpression : public Instruction {
protected:
    /**
     * Construct an IrExpression node
     */
    constexpr explicit IrExpression(
        const IrKind kind,
        NamedValue* result
    )
    : Instruction(kind)
    , m_result(result) {}

public:
    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const Instruction* node) -> bool {
        return node->getKind() >= IrKind::Cast && node->getKind() <= IrKind::Ge;
    }

    /// Get the result
    [[nodiscard]] constexpr auto getResult() const -> NamedValue* {
        return m_result;
    }

private:
    NamedValue* m_result;
};

/**
 * Type conversion
 */
class [[nodiscard]] CastInstr final : public IrExpression {
public:
    /**
     * Construct a CastInstr node
     */
    constexpr CastInstr(
        NamedValue* result,
        const Type* targetType,
        Value* operand
    )
    : IrExpression(IrKind::Cast, result)
    , m_targetType(targetType)
    , m_operand(operand) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const Instruction* node) -> bool {
        return node->getKind() == IrKind::Cast;
    }

    /// Get the targetType
    [[nodiscard]] constexpr auto getTargetType() const -> const Type* {
        return m_targetType;
    }

    /// Get the operand
    [[nodiscard]] constexpr auto getOperand() const -> Value* {
        return m_operand;
    }

private:
    const Type* m_targetType;
    Value* m_operand;
};

/**
 * Load value through pointer
 */
class [[nodiscard]] LoadInstr final : public IrExpression {
public:
    /**
     * Construct a LoadInstr node
     */
    constexpr LoadInstr(
        NamedValue* result,
        Value* source
    )
    : IrExpression(IrKind::Load, result)
    , m_source(source) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const Instruction* node) -> bool {
        return node->getKind() == IrKind::Load;
    }

    /// Get the source
    [[nodiscard]] constexpr auto getSource() const -> Value* {
        return m_source;
    }

private:
    Value* m_source;
};

/**
 * Take address of a variable
 */
class [[nodiscard]] AddrOfInstr final : public IrExpression {
public:
    /**
     * Construct an AddrOfInstr node
     */
    constexpr AddrOfInstr(
        NamedValue* result,
        Value* operand
    )
    : IrExpression(IrKind::AddrOf, result)
    , m_operand(operand) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const Instruction* node) -> bool {
        return node->getKind() == IrKind::AddrOf;
    }

    /// Get the operand
    [[nodiscard]] constexpr auto getOperand() const -> Value* {
        return m_operand;
    }

private:
    Value* m_operand;
};

/**
 * Call a function
 */
class [[nodiscard]] CallInstr final : public IrExpression {
public:
    /**
     * Construct a CallInstr node
     */
    constexpr CallInstr(
        NamedValue* result,
        Function* callee,
        const std::span<Value*> args
    )
    : IrExpression(IrKind::Call, result)
    , m_callee(callee)
    , m_args(args) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const Instruction* node) -> bool {
        return node->getKind() == IrKind::Call;
    }

    /// Get the callee
    [[nodiscard]] constexpr auto getCallee() const -> Function* {
        return m_callee;
    }

    /// Get the args
    [[nodiscard]] constexpr auto getArgs() const -> std::span<Value*> {
        return m_args;
    }

private:
    Function* m_callee;
    std::span<Value*> m_args;
};

// -----------------------------------------------------------------------------
// Unary nodes
// -----------------------------------------------------------------------------

/**
 * Abstract base for all Unary expressions nodes
 */
class [[nodiscard]] IrUnary : public IrExpression {
protected:
    /**
     * Construct an IrUnary node
     */
    constexpr IrUnary(
        const IrKind kind,
        NamedValue* result,
        Value* operand
    )
    : IrExpression(kind, result)
    , m_operand(operand) {}

public:
    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const Instruction* node) -> bool {
        return node->getKind() >= IrKind::Neg && node->getKind() <= IrKind::Not;
    }

    /// Get the operand
    [[nodiscard]] constexpr auto getOperand() const -> Value* {
        return m_operand;
    }

private:
    Value* m_operand;
};

/**
 * Arithmetic negation
 */
class [[nodiscard]] NegInstr final : public IrUnary {
public:
    /**
     * Construct a NegInstr node
     */
    constexpr NegInstr(
        NamedValue* result,
        Value* operand
    )
    : IrUnary(IrKind::Neg, result, operand) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const Instruction* node) -> bool {
        return node->getKind() == IrKind::Neg;
    }
};

/**
 * Logical NOT
 */
class [[nodiscard]] NotInstr final : public IrUnary {
public:
    /**
     * Construct a NotInstr node
     */
    constexpr NotInstr(
        NamedValue* result,
        Value* operand
    )
    : IrUnary(IrKind::Not, result, operand) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const Instruction* node) -> bool {
        return node->getKind() == IrKind::Not;
    }
};

// -----------------------------------------------------------------------------
// Binary nodes
// -----------------------------------------------------------------------------

/**
 * Abstract base for all Binary expressions nodes
 */
class [[nodiscard]] IrBinary : public IrExpression {
protected:
    /**
     * Construct an IrBinary node
     */
    constexpr IrBinary(
        const IrKind kind,
        NamedValue* result,
        Value* lhs,
        Value* rhs
    )
    : IrExpression(kind, result)
    , m_lhs(lhs)
    , m_rhs(rhs) {}

public:
    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const Instruction* node) -> bool {
        return node->getKind() >= IrKind::Add && node->getKind() <= IrKind::Ge;
    }

    /// Get the lhs
    [[nodiscard]] constexpr auto getLhs() const -> Value* {
        return m_lhs;
    }

    /// Get the rhs
    [[nodiscard]] constexpr auto getRhs() const -> Value* {
        return m_rhs;
    }

private:
    Value* m_lhs;
    Value* m_rhs;
};

/**
 * Addition
 */
class [[nodiscard]] AddInstr final : public IrBinary {
public:
    /**
     * Construct an AddInstr node
     */
    constexpr AddInstr(
        NamedValue* result,
        Value* lhs,
        Value* rhs
    )
    : IrBinary(IrKind::Add, result, lhs, rhs) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const Instruction* node) -> bool {
        return node->getKind() == IrKind::Add;
    }
};

/**
 * Subtraction
 */
class [[nodiscard]] SubInstr final : public IrBinary {
public:
    /**
     * Construct a SubInstr node
     */
    constexpr SubInstr(
        NamedValue* result,
        Value* lhs,
        Value* rhs
    )
    : IrBinary(IrKind::Sub, result, lhs, rhs) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const Instruction* node) -> bool {
        return node->getKind() == IrKind::Sub;
    }
};

/**
 * Multiplication
 */
class [[nodiscard]] MulInstr final : public IrBinary {
public:
    /**
     * Construct a MulInstr node
     */
    constexpr MulInstr(
        NamedValue* result,
        Value* lhs,
        Value* rhs
    )
    : IrBinary(IrKind::Mul, result, lhs, rhs) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const Instruction* node) -> bool {
        return node->getKind() == IrKind::Mul;
    }
};

/**
 * Division
 */
class [[nodiscard]] DivInstr final : public IrBinary {
public:
    /**
     * Construct a DivInstr node
     */
    constexpr DivInstr(
        NamedValue* result,
        Value* lhs,
        Value* rhs
    )
    : IrBinary(IrKind::Div, result, lhs, rhs) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const Instruction* node) -> bool {
        return node->getKind() == IrKind::Div;
    }
};

/**
 * Modulo
 */
class [[nodiscard]] ModInstr final : public IrBinary {
public:
    /**
     * Construct a ModInstr node
     */
    constexpr ModInstr(
        NamedValue* result,
        Value* lhs,
        Value* rhs
    )
    : IrBinary(IrKind::Mod, result, lhs, rhs) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const Instruction* node) -> bool {
        return node->getKind() == IrKind::Mod;
    }
};

/**
 * Logical AND
 */
class [[nodiscard]] AndInstr final : public IrBinary {
public:
    /**
     * Construct an AndInstr node
     */
    constexpr AndInstr(
        NamedValue* result,
        Value* lhs,
        Value* rhs
    )
    : IrBinary(IrKind::And, result, lhs, rhs) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const Instruction* node) -> bool {
        return node->getKind() == IrKind::And;
    }
};

/**
 * Logical OR
 */
class [[nodiscard]] OrInstr final : public IrBinary {
public:
    /**
     * Construct an OrInstr node
     */
    constexpr OrInstr(
        NamedValue* result,
        Value* lhs,
        Value* rhs
    )
    : IrBinary(IrKind::Or, result, lhs, rhs) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const Instruction* node) -> bool {
        return node->getKind() == IrKind::Or;
    }
};

// -----------------------------------------------------------------------------
// Comparison nodes
// -----------------------------------------------------------------------------

/**
 * Abstract base for all Comparison expressions nodes
 */
class [[nodiscard]] IrComparison : public IrBinary {
protected:
    using IrBinary::IrBinary;

public:
    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const Instruction* node) -> bool {
        return node->getKind() >= IrKind::Eq && node->getKind() <= IrKind::Ge;
    }
};

/**
 * Equal
 */
class [[nodiscard]] EqInstr final : public IrComparison {
public:
    /**
     * Construct an EqInstr node
     */
    constexpr EqInstr(
        NamedValue* result,
        Value* lhs,
        Value* rhs
    )
    : IrComparison(IrKind::Eq, result, lhs, rhs) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const Instruction* node) -> bool {
        return node->getKind() == IrKind::Eq;
    }
};

/**
 * Not equal
 */
class [[nodiscard]] NeInstr final : public IrComparison {
public:
    /**
     * Construct a NeInstr node
     */
    constexpr NeInstr(
        NamedValue* result,
        Value* lhs,
        Value* rhs
    )
    : IrComparison(IrKind::Ne, result, lhs, rhs) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const Instruction* node) -> bool {
        return node->getKind() == IrKind::Ne;
    }
};

/**
 * Less than
 */
class [[nodiscard]] LtInstr final : public IrComparison {
public:
    /**
     * Construct a LtInstr node
     */
    constexpr LtInstr(
        NamedValue* result,
        Value* lhs,
        Value* rhs
    )
    : IrComparison(IrKind::Lt, result, lhs, rhs) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const Instruction* node) -> bool {
        return node->getKind() == IrKind::Lt;
    }
};

/**
 * Less than or equal
 */
class [[nodiscard]] LeInstr final : public IrComparison {
public:
    /**
     * Construct a LeInstr node
     */
    constexpr LeInstr(
        NamedValue* result,
        Value* lhs,
        Value* rhs
    )
    : IrComparison(IrKind::Le, result, lhs, rhs) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const Instruction* node) -> bool {
        return node->getKind() == IrKind::Le;
    }
};

/**
 * Greater than
 */
class [[nodiscard]] GtInstr final : public IrComparison {
public:
    /**
     * Construct a GtInstr node
     */
    constexpr GtInstr(
        NamedValue* result,
        Value* lhs,
        Value* rhs
    )
    : IrComparison(IrKind::Gt, result, lhs, rhs) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const Instruction* node) -> bool {
        return node->getKind() == IrKind::Gt;
    }
};

/**
 * Greater than or equal
 */
class [[nodiscard]] GeInstr final : public IrComparison {
public:
    /**
     * Construct a GeInstr node
     */
    constexpr GeInstr(
        NamedValue* result,
        Value* lhs,
        Value* rhs
    )
    : IrComparison(IrKind::Ge, result, lhs, rhs) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const Instruction* node) -> bool {
        return node->getKind() == IrKind::Ge;
    }
};

// -----------------------------------------------------------------------------
// Declaration nodes
// -----------------------------------------------------------------------------

/**
 * Abstract base for all Declaration instructions nodes
 */
class [[nodiscard]] IrDeclaration : public Instruction {
protected:
    /**
     * Construct an IrDeclaration node
     */
    constexpr explicit IrDeclaration(
        const IrKind kind,
        NamedValue* result
    )
    : Instruction(kind)
    , m_result(result) {}

public:
    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const Instruction* node) -> bool {
        return node->getKind() == IrKind::Var;
    }

    /// Get the result
    [[nodiscard]] constexpr auto getResult() const -> NamedValue* {
        return m_result;
    }

private:
    NamedValue* m_result;
};

/**
 * Variable declaration
 */
class [[nodiscard]] VarInstr final : public IrDeclaration {
public:
    /**
     * Construct a VarInstr node
     */
    constexpr VarInstr(
        NamedValue* result,
        const Type* type
    )
    : IrDeclaration(IrKind::Var, result)
    , m_type(type) {}

    /// LLVM RTTI support
    [[nodiscard]] static constexpr auto classof(const Instruction* node) -> bool {
        return node->getKind() == IrKind::Var;
    }

    /// Get the type
    [[nodiscard]] constexpr auto getType() const -> const Type* {
        return m_type;
    }

private:
    const Type* m_type;
};

} // namespace lbc::ir::lib
